[format]
# https://docs.astral.sh/ruff/settings/#format
line-ending = "lf"  # Use UNIX `\n` line endings for all files

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "NPY",  # numpy
    "PL",   # pylint
    "UP",   # pyupgrade
    "W",    # pycodestyle warnings
]

[lint.per-file-ignores]
"docs/clay_over_aoi.ipynb" = ["E501"]
"finetune/embedder/how-to-embed.ipynb" = ["E501", "PLR2004"]
"finetune/segment/chesapeake_inference.ipynb" = ["PLR0913"]
"finetune/regression/biomasters_inference.ipynb" = ["PLR0913"]
"scripts/worldcover/worldcover_vrt.py" = ["E501"]
"claymodel/__init__.py" = ["PLR0911"]
"claymodel/api.py" = ["PLC0415", "PLR0912", "PLR0915", "PLR2004"]
"claymodel/module.py" = ["PLR2004"]
"claymodel/inference/elle.py" = ["PLC0415"]
"claymodel/inference/masking.py" = ["PLR2004"]
"tests/*.py" = ["PLC0415", "PLR2004"]

[lint.pylint]
max-args = 6
