# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/model",
        "doc_host": "https://Clay-foundation.github.io",
        "git_url": "https://github.com/Clay-foundation/model",
        "lib_path": "clay",
    },
    "syms": {
        "clay.core": {"clay.core.foo": ("core.html#foo", "clay/core.py")},
        "clay.embeddings": {
            "clay.embeddings.EmbeddingsFactory": (
                "embeddings.html#embeddingsfactory",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsFactory.__init__": (
                "embeddings.html#embeddingsfactory.__init__",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsFactory._save_embeddings": (
                "embeddings.html#embeddingsfactory._save_embeddings",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsFactory.generate_embeddings": (
                "embeddings.html#embeddingsfactory.generate_embeddings",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsHandler": (
                "embeddings.html#embeddingshandler",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsHandler.__init__": (
                "embeddings.html#embeddingshandler.__init__",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsHandler.image_sample": (
                "embeddings.html#embeddingshandler.image_sample",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsHandler.load_data": (
                "embeddings.html#embeddingshandler.load_data",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsHandler.local_imgs": (
                "embeddings.html#embeddingshandler.local_imgs",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsHandler.plot": (
                "embeddings.html#embeddingshandler.plot",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsHandler.read_embeddings_file": (
                "embeddings.html#embeddingshandler.read_embeddings_file",
                "clay/embeddings.py",
            ),
            "clay.embeddings.EmbeddingsHandler.transform_crs": (
                "embeddings.html#embeddingshandler.transform_crs",
                "clay/embeddings.py",
            ),
        },
    },
}
