_target_: pangaea.encoders.clay_encoder.Clay_Encoder
encoder_weights: ./pretrained_models/clay_v1.5.0_epoch-07_val-loss-0.1718.ckpt
download_url: https://huggingface.co/made-with-clay/Clay/resolve/main/clay_v1.5.0_epoch-07_val-loss-0.1718.ckpt

embed_dim: 768
input_size: 224
in_chans: 6
patch_size: 8
num_heads: 12
depth: 12
mlp_ratio: 4
mask_ratio: 0.75

input_bands:
  optical:
    - B2
    - B3
    - B4
    - B8A
    - B11
    - B12

output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 768